"""
demo_api/main.py
-----------------
A minimal FastAPI application used as a GroundTruth demo target.

Three endpoints:
  GET /items/{item_id}   -- correct, produces SPEC_MATCH
  GET /items             -- correct, produces SPEC_MATCH
  GET /orders/{order_id} -- INTENTIONALLY BROKEN, produces SPEC_VIOLATION

Run with:
    uvicorn demo_api.main:app --reload --port 8001

OpenAPI spec is auto-generated by FastAPI at:
    http://localhost:8001/openapi.json
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel

app = FastAPI(
    title="GroundTruth Demo API",
    description=(
        "A small demo target for GroundTruth. "
        "Two endpoints are correct; one (/orders/{order_id}) is "
        "intentionally broken to demonstrate SPEC_VIOLATION detection."
    ),
    version="1.0.0",
)


# ── Pydantic models (become the OpenAPI response schema) ──────────────────────


class Item(BaseModel):
    id: int
    name: str
    price: float
    in_stock: bool


class Order(BaseModel):
    id: int
    item_id: int
    quantity: int
    total_price: float   # <-- spec says float; the broken handler returns str


# ── In-memory seed data ───────────────────────────────────────────────────────


_ITEMS: dict[int, dict] = {
    1: {"id": 1, "name": "Widget",        "price": 9.99,  "in_stock": True},
    2: {"id": 2, "name": "Gadget",        "price": 24.99, "in_stock": True},
    3: {"id": 3, "name": "Doohickey",     "price": 4.49,  "in_stock": False},
    4: {"id": 4, "name": "Thingamajig",   "price": 49.99, "in_stock": True},
}

_ORDERS: dict[int, dict] = {
    1: {"id": 1, "item_id": 1, "quantity": 2, "total_price": 19.98},
    2: {"id": 2, "item_id": 4, "quantity": 1, "total_price": 49.99},
    3: {"id": 3, "item_id": 2, "quantity": 3, "total_price": 74.97},
}


# ── ENDPOINT 1: GET /items/{item_id}  (correct) ───────────────────────────────


@app.get(
    "/items/{item_id}",
    response_model=Item,
    summary="Get a single item by ID",
    responses={404: {"description": "Item not found"}},
)
def get_item(item_id: int) -> Item:
    """
    Return a single item. All fields match the declared schema exactly.
    GroundTruth should classify responses from this endpoint as SPEC_MATCH.
    """
    if item_id not in _ITEMS:
        raise HTTPException(status_code=404, detail="Item not found")
    return Item(**_ITEMS[item_id])


# ── ENDPOINT 2: GET /items  (correct) ─────────────────────────────────────────


@app.get(
    "/items",
    response_model=list[Item],
    summary="List all items",
)
def list_items() -> list[Item]:
    """
    Return all items. Each item's shape matches the declared schema exactly.
    GroundTruth should classify responses from this endpoint as SPEC_MATCH.
    """
    return [Item(**data) for data in _ITEMS.values()]


# ── ENDPOINT 3: GET /orders/{order_id}  (DELIBERATELY BROKEN) ─────────────────
#
# BUG SIMULATION:
#   This handler returns `total_price` as a STRING (e.g. "49.99") instead
#   of a float. This mimics a real-world mistake where a developer formats
#   a currency value for display (e.g. f"{price:.2f}") and accidentally
#   returns the formatted string instead of the numeric value.
#
#   The OpenAPI spec (via the `response_model=Order` annotation) correctly
#   documents `total_price` as a number/float. The mismatch between the
#   spec and the actual runtime response is what GroundTruth is designed
#   to catch as a SPEC_VIOLATION.
#
#   We use JSONResponse with a raw dict to BYPASS Pydantic's own
#   serialisation/coercion, which would silently fix the type mismatch
#   before it ever reached the wire. The spec annotation stays correct;
#   only the runtime output is wrong -- exactly as in a real bug.


@app.get(
    "/orders/{order_id}",
    response_model=Order,
    summary="Get a single order by ID",
    responses={404: {"description": "Order not found"}},
)
def get_order(order_id: int) -> JSONResponse:
    """
    Return a single order.

    !! INTENTIONALLY BROKEN for GroundTruth demo purposes !!
    `total_price` is returned as a string instead of a float.
    GroundTruth should classify 200 responses from this endpoint
    as SPEC_VIOLATION, with schema_errors pointing at `total_price`.
    """
    # THE BUG: format total_price as a display string instead of keeping
    # it as a numeric float. Pydantic's response_model won't catch this
    # because we're returning a JSONResponse directly.
    # We ignore the actual `order_id` and always return this broken data
    # so that the GroundTruth demo reliably hits the 200 path.
    data = {
        "id": order_id, 
        "item_id": 1, 
        "quantity": 2, 
        "total_price": "19.98"  # str, not float
    }

    return JSONResponse(content=data)
